sudo: false
language: node_js
node_js:
- '0.12'
notifications:
  email: simone.desordi@gmail.com
deploy:
  provider: heroku
  api_key:
    secure: ht/+iFDX8QNl2tYCFDBhAnHPjbs8kj4lGgJ44GN1C1XfcFIy81nD3DEsDlH3HWaATOZMsFvMPurMsaLTe9c9eiZbLLJig8ST9x6kgSYIlgqws/X0fW51rSxM+0Mh5AndDQheW7/6QwhqBk6DJVZswgwtekvTLrw++KgxQQT3iwtmxtkiT21MH1d54RWKOYYmsBae4CTCJQI+mTdkDkLEewmJnOc3NvPRTRcMEYTddjB2nXTPVobkj+VRRYbRS+B5I45amybjD4A5nk/2dbxqiKMdQGZ/6h1xiDP4a9bNsOWCxV8W3F07SZF0NgvSE4TWwhAnypXHW/6Xdpnz1M9HS5qHVF+8BTqN/csrS1KjDQ4g3wb9aPDXq+wo9LHVssmzZNF0ukQQQT5IQh1Vdb/X1Qs9YNzhuMVTG4Nux2DvRssBDmSkKl7zDweOB1fFaPGWuQyIe0gj639mqOx3CIPua5Eieb8B28xSP4MzHBebYBWl7Aw35uYef+SIs8c696MOCT+4StrDUWZiuIh6dnmbpyKg+gWvpJ21Xh1vMI6NaeeuhnELYC3IApBDJklS5Zjc8C1nzzazKRRCE+MD+dowqx+pDdhPV9SA0+eVYnN2e8WaAulErJ3pv+7oIQ4hCY2ppqLOnEuWuQB1air/BncrpYx75U6AudB3eh6V7/sZVEo=
  app: send-web
  on:
    repo: simonedesordi/send-web

